# Generated by Django 4.0.1 on 2022-01-15 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_comment_author_comment_date_alter_comment_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-date',), 'verbose_name': 'پست', 'verbose_name_plural': 'پست ها'},
        ),
    ]
