# Generated by Django 4.0.1 on 2022-01-18 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-date',), 'verbose_name': 'نظر', 'verbose_name_plural': 'نظرات'},
        ),
    ]
